FROM python:3.11-slim-buster

# Update system
RUN apt-get update && apt-get install -y build-essential \
    && apt-get -y upgrade

# Install curl
RUN apt-get install -y git

# Set the working directory in the container to /app
WORKDIR /app

# Clone the ageml GitHub repository
RUN cd /app && git clone https://github.com/compneurobilbao/ageml.git \
    && cd ageml \
    && pip install -e . \
    && cd /app

# Modify entrypoint
ENTRYPOINT [ "/bin/bash" ]
