name: TestCov Lint

on:
  push:
    branches:
      - main
      - release-*
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Dependency installation
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry nox nox-poetry
    - name: TestCoverage
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      run: |
        nox -s coverage
    - name: Linting
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      run: |
        nox -s lint